---
- name: start odoo whitelists
  docker_compose:
    project_src: /home/docker
    files: whitelists.yaml
    project_name: whitelists

- name: pull odoo ML image
  docker_image:
    name: lefilament/odoo:{{ instance_odoo_version }}_ml
    source: pull
    force_source: true
  when: not ansible_check_mode and odoo_multilingual is defined and odoo_multilingual

- name: pull odoo Python3.6 image
  docker_image:
    name: lefilament/odoo:{{ instance_odoo_version }}_py3.6
    source: pull
    force_source: true
  when: not ansible_check_mode and odoo_python36 is defined and odoo_python36

- name: pull odoo image
  docker_image:
    name: lefilament/odoo:{{ instance_odoo_version }}
    source: pull
    force_source: true
  when: not ansible_check_mode and (odoo_multilingual is not defined or not odoo_multilingual) and (odoo_python36 is not defined or not odoo_python36)

- name: build odoo image
  docker_compose:
    project_src: /home/docker/{{ instance_name }}/
    build: true
    nocache: true
    recreate: always
    restarted: true
    remove_orphans: true
  async: 600
  poll: 10
  when: not ansible_check_mode

- name: start odoo container
  docker_compose:
    project_src: /home/docker/{{ instance_name }}/
    remove_orphans: true
  when: not ansible_check_mode

- name: remove intermediate image
  docker_prune:
    builder_cache: true
    images: true
    images_filters:
      label: stage=builder
  when: not ansible_check_mode and inventory_hostname not in groups['maintenance_contract']

- name: remove ssh private keys
  file:
    path: "/home/docker/{{ instance_name }}/odoo/id_ed25519.sources"
    state: absent
  when: not ansible_check_mode and inventory_hostname not in groups['maintenance_contract']
